### ISSUE TITLE
can i use official nano image 

### ISSUE THREAD

**Issue by traderpedroso** [linuxserver/docker-nano#3]
I found the way of deploying genesis fantastic! is docker image  source code available? like for example change the prefix of wallet or even use the official image of the nano is there any way to use your script in the official image to start from scratch  using the scripts

**Comment by aptalca** [comment]
Here's the binstage build dockerfile:
https://github.com/linuxserver/docker-nano/blob/bin-stable/Dockerfile

**Comment by traderpedroso** [comment]
> Here's the binstage build dockerfile:
> https://github.com/linuxserver/docker-nano/blob/bin-stable/Dockerfile

thanks man !
this  project is fantastic! i spent 3 weeks compiling and creating it from scratch based on banano and even then it was not very stable but with this project passed all the network stress and stability tests
